export const CYCLIC_COMMISISON_UPLOAD = 'CYCLIC_COMMISISON_UPLOAD'
export const CYCLIC_COMMISISON_UPLOAD_DETAILS = 'CYCLIC_COMMISISON_UPLOAD_DETAILS'
export const CYCLIC_COMMISISON_UPLOAD_ITEM_DETAILS = 'CYCLIC_COMMISISON_UPLOAD_ITEM_DETAILS'

export const CYCLIC_COMMISISON_SUCCESS = 'CYCLIC_COMMISISON_SUCCESS'
export const CYCLIC_COMMISISON_SUCCESS_DETAILS = 'CYCLIC_COMMISISON_SUCCESS_DETAILS'
export const CYCLIC_COMMISISON_SUCCESS_ITEM_DETAILS = 'CYCLIC_COMMISISON_SUCCESS_ITEM_DETAILS'

export const CYCLIC_COMMISISON_FAIL = 'CYCLIC_COMMISISON_FAIL'
export const CYCLIC_COMMISISON_FAIL_DETAILS = 'CYCLIC_COMMISISON_FAIL_DETAILS'
export const CYCLIC_COMMISISON_FAIL_ITEM_DETAILS = 'CYCLIC_COMMISISON_FAIL_ITEM_DETAILS'
