export const NAE_UPLOAD_NEWS = 'NAE_UPLOAD_NEWS'
export const NAE_UPLOAD_NEWS_DETAILS = 'NAE_UPLOAD_NEWS_DETAILS'
export const NAE_UPLOAD_EVENTS = 'NAE_UPLOAD_EVENTS'
export const NAE_UPLOAD_EVENTS_DETAILS = 'NAE_UPLOAD_EVENTS_DETAILS'

export const NAE_SUCCESS_NEWS = 'NAE_SUCCESS_NEWS'
export const NAE_SUCCESS_NEWS_DETAILS = 'NAE_SUCCESS_NEWS_DETAILS'
export const NAE_SUCCESS_EVENTS = 'NAE_SUCCESS_EVENTS'
export const NAE_SUCCESS_EVENTS_DETAILS = 'NAE_SUCCESS_EVENTS_DETAILS'

export const NAE_FAIL_NEWS = 'NAE_FAIL_NEWS'
export const NAE_FAIL_EVENTS = 'NAE_FAIL_EVENTS'
export const NAE_FAIL_NEWS_DETAILS = 'NAE_FAIL_NEWS_DETAILS'
export const NAE_FAIL_EVENTS_DETAILS = 'NAE_FAIL_EVENTS_DETAILS'
